// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahxncedumnyeipizkbwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeG5jZWR1bW55ZWlwaXprYndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDEwNzYsImV4cCI6MjA2MzU3NzA3Nn0.Pa5KngwAnd4J0P5Yb5s15jxnrv3ecB50KzZYXksoeCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a public client for regular user operations
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create an admin client for admin operations
export const supabaseAdmin = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);
